name: Compile and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install dependencies
      run: |
        echo "deb http://azure.archive.ubuntu.com/ubuntu eoan main universe" | sudo tee /etc/apt/sources.list
        sudo apt update
        sudo apt install libfl-dev libbison-dev libyaml-cpp-dev libgsl-dev
    - name: Prepare to build DFTCalc
      run: mkdir build && cd build && cmake -DDFTROOT=$GITHUB_WORKSPACE/dftroot ..
    - name: Compile DFTCalc
      run: cd build && make -j4 install
    - name: Checkout DFTRES
      uses: actions/checkout@v2
      with:
        repository: utwente-fmt/DFTRES
        path: DFTRES
    - name: Set PATH
      run: echo ::set-env name=PATH::$(echo $PATH:${{github.workspace}}/imrmc/bin:${{github.workspace}}/dftroot/bin)
    - name: Get cache revisions
      id: cache-revs
      run: |
        cd DFTRES && echo "::set-output name=dftres::$(git rev-parse HEAD)"
        echo "::set-output name=imrmc::$(git ls-remote git://git.ennoruijters.nl/imrmc.git | grep '\srefs/heads/master$' | grep -o '^[0-9a-z]\+')"
        echo "::set-output name=imrmc-march::$(gcc -march=native -E -v - </dev/null 2>&1 | grep cc1 | sha256sum | grep -o '^[0-9a-z]\+')"
    - name: Cache DFTRES
      id: cache-dftres
      uses: actions/cache@v2
      with:
        path: DFTRES/DFTRES.jar
        key: ${{ runner.os }}-dftres-${{ steps.cache-revs.outputs.dftres }}
    - name: Compile DFTRES if needed
      if: steps.cache-dftres.outputs.cache-hit != 'true'
      run: cd DFTRES && make jar
    - name: Cache IMRMC
      id: cache-imrmc
      uses: actions/cache@v2
      with:
        path: imrmc/bin/imrmc
        key: ${{ runner.os }}-imrmc-${{ steps.cache-revs.outputs.imrmc }}-${{ steps.cache-revs.outputs.imrmc-march }}
    - name: Checkout IMRMC
      if: steps.cache-imrmc.outputs.cache-hit != 'true'
      run: git clone --depth 1 git://git.ennoruijters.nl/imrmc.git imrmc
    - name: Compile IMRMC
      if: steps.cache-imrmc.outputs.cache-hit != 'true'
      run: cd imrmc && make all -j4
    - name: Tests
      env:
        DFTRES: ${{github.workspace}}/DFTRES
      run: cd test && bash test.sh --exact --imrmc
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: test-results
        path: test/output
